"""copy_text.py — every word on the page, English and Thai. research/facts.txt holds the sources
behind each line; SOURCES at the bottom is what the page prints."""

UI = {"en": {}, "th": {}}

DAYS = ["2026-10-10", "2026-10-11", "2026-10-12", "2026-10-13", "2026-10-14", "2026-10-15", "2026-10-16", "2026-10-17", "2026-10-18"]

# name, colour in the wok, jay?, why not
FOODS = {
 "en": [
  ("Tofu", "#f6efd8", True, ""), ("Shiitake", "#7a5236", True, ""), ("Chinese kale", "#3f8f3a", True, ""),
  ("Rice noodles", "#fbf7ea", True, ""), ("Soy sauce", "#3b1d0e", True, ""), ("Gluten 'pork'", "#b9422e", True, ""),
  ("Coconut milk", "#fffdf5", True, ""), ("Bamboo shoot", "#e6d38a", True, ""),
  ("Garlic", "#f3eee0", False, "the first of the five pungent plants"),
  ("Shallot", "#b0566a", False, "onions of every kind are among the five pungent plants"),
  ("Spring onion", "#7cc35a", False, "onions of every kind are among the five pungent plants"),
  ("Garlic chives", "#4f9e3e", False, "one of the five pungent plants"),
  ("Coriander", "#69b04a", False, "on some lists, not on others; strict kitchens leave it out"),
  ("Egg", "#ffd34d", False, "jay leaves out eggs"),
  ("Fish sauce", "#8a4a18", False, "made from fish"),
  ("Oyster sauce", "#4a2a1a", False, "made from oysters"),
  ("Cow's milk", "#ffffff", False, "jay leaves out milk and everything made from it"),
  ("Honey", "#e9a21a", False, "made by bees; Thai Wikipedia lists it with the animal products"),
  ("Pork", "#e98a8a", False, "meat"),
 ],
 "th": [
  ("เต้าหู้", "#f6efd8", True, ""), ("เห็ดหอม", "#7a5236", True, ""), ("ผักคะน้า", "#3f8f3a", True, ""),
  ("เส้นก๋วยเตี๋ยว", "#fbf7ea", True, ""), ("ซีอิ๊วขาว", "#3b1d0e", True, ""), ("หมูแดงเจ", "#b9422e", True, ""),
  ("กะทิ", "#fffdf5", True, ""), ("หน่อไม้", "#e6d38a", True, ""),
  ("กระเทียม", "#f3eee0", False, "ผักฉุนอันดับแรกในห้าอย่าง"),
  ("หอมแดง", "#b0566a", False, "หอมทุกชนิดอยู่ในผักฉุนห้าอย่าง"),
  ("ต้นหอม", "#7cc35a", False, "หอมทุกชนิดอยู่ในผักฉุนห้าอย่าง"),
  ("กุยช่าย", "#4f9e3e", False, "หนึ่งในผักฉุนห้าอย่าง"),
  ("ผักชี", "#69b04a", False, "บางตำรานับ บางตำราไม่นับ ครัวที่เคร่งไม่ใส่"),
  ("ไข่", "#ffd34d", False, "เจงดไข่"),
  ("น้ำปลา", "#8a4a18", False, "ทำจากปลา"),
  ("ซอสหอยนางรม", "#4a2a1a", False, "ทำจากหอยนางรม"),
  ("นมวัว", "#ffffff", False, "เจงดนมและของที่ทำจากนม"),
  ("น้ำผึ้ง", "#e9a21a", False, "มาจากผึ้ง วิกิพีเดียภาษาไทยนับไว้กับของจากสัตว์"),
  ("หมู", "#e98a8a", False, "เนื้อสัตว์"),
 ],
}

DISHES = {
 "en": [
  ("noodle", "Phat mi sua jay", "", "stir-fried longevity noodles", "Thin Fujian wheat noodles, fried with cabbage, shiitake and tofu. The festival's must-have."),
  ("soup", "Tom chap chai jay", "雜菜", "mixed-vegetable stew", "Daikon, bok choy, cabbage and celery with tofu. Hokkien for 'mixed vegetables'."),
  ("soup", "Sup yuea phai jay", "", "bamboo-fungus soup", "Clear hot soup of bamboo fungus."),
  ("rice", "Khao tom jay with kana chai", "", "rice porridge and pickled greens", "Porridge on all day, with kana chai, a Chinese pickled green."),
  ("rice", "Khao phat nam liap jay", "", "fried rice with Chinese black olive", "Rice fried with salted Chinese black olive."),
  ("curry", "Kaeng khiao wan jay", "", "jay green curry", "Coconut milk, vegetables, tofu. No shrimp paste, no garlic in the paste."),
  ("curry", "Khanom chin nam ya jay", "", "rice noodles with jay curry sauce", "Fermented rice noodles under jay curry. Free at Pung Tao Kong in 2023."),
  ("curry", "Hor mok jay", "", "steamed curry in banana leaf", "Steamed curry custard in banana leaf, with tofu or mushroom."),
  ("noodle", "Rat na jay", "", "noodles in gravy", "Wide noodles, thick gravy, baby corn, kale."),
  ("noodle", "Kuai chap yuan jay", "", "rolled rice-noodle soup", "Rolled rice noodles in clear broth, with tofu."),
  ("rice", "Phat makhuea jay", "", "stir-fried aubergine", "Long aubergine, stir-fried."),
  ("rice", "Larb jay", "", "minced salad, jay", "Tofu, mushroom or fried flour, dressed as larb. Sold at Warorot in 2025."),
  ("rice", "Nam phrik num jay", "", "northern green-chilli dip", "Grilled green chillies, pounded, no fish sauce or garlic."),
  ("rice", "Mu daeng jay", "", "red 'pork', from gluten", "Gluten or soy protein made to look like Chinese red pork."),
  ("snack", "Tao hu thot, phueak thot", "", "fried tofu, fried taro", "Tofu, taro, daikon and corn, fried."),
  ("snack", "Fong tao hu thot", "", "fried tofu skin", "Skin lifted off hot soy milk, dried, fried crisp."),
  ("snack", "Po pia thot jay", "", "fried spring rolls", "KTC's easy festival snack."),
  ("sweet", "Nam tao hu", "豆漿", "soy milk", "Hot soy milk, often with grains."),
  ("sweet", "Tao huai nam khing", "豆花", "tofu pudding in ginger syrup", "Soft tofu in hot ginger syrup."),
  ("sweet", "Bua loi phueak", "", "taro dumplings in coconut milk", "Taro dumplings in warm coconut milk."),
  ("sweet", "Kluai buat chi", "", "bananas in coconut milk", "Bananas simmered in sweet coconut milk."),
 ],
 "th": [
  ("noodle", "ผัดหมี่ซั่วเจ", "", "หมี่อายุยืน", "หมี่ซั่วเส้นเล็กจากฮกเกี้ยน ผัดกับกะหล่ำปลี เห็ดหอม เต้าหู้ เมนูที่ขาดไม่ได้"),
  ("soup", "ต้มจับฉ่ายเจ", "雜菜", "ผักรวมต้ม", "หัวไชเท้า กวางตุ้ง กะหล่ำปลี ขึ้นฉ่าย กับเต้าหู้ จับฉ่ายคือผักรวมในภาษาฮกเกี้ยน"),
  ("soup", "ซุปเยื่อไผ่เจ", "", "ซุปเห็ดเยื่อไผ่", "ซุปใสร้อน ๆ ใส่เยื่อไผ่"),
  ("rice", "ข้าวต้มเจกับกานาฉ่าย", "", "ข้าวต้มกับผักดอง", "ข้าวต้มหม้อใหญ่ทั้งวัน กับกานาฉ่ายผักดองจีน"),
  ("rice", "ข้าวผัดหนำเลี้ยบเจ", "", "ข้าวผัดหนำเลี้ยบ", "ข้าวผัดกับหนำเลี้ยบดองเกลือ"),
  ("curry", "แกงเขียวหวานเจ", "", "แกงเขียวหวาน ไม่ใส่กะปิกับกระเทียม", "กะทิ ผัก เต้าหู้ พริกแกงไม่มีกะปิไม่มีกระเทียม"),
  ("curry", "ขนมจีนน้ำยาเจ", "", "ขนมจีนราดน้ำยาเจ", "ขนมจีนราดน้ำยาเจ ศาลเจ้าปุงเถ่ากงเลี้ยงฟรีปี 2566"),
  ("curry", "ห่อหมกเจ", "", "ห่อหมกใบตอง", "ห่อหมกนึ่งใบตอง ใช้เต้าหู้หรือเห็ด"),
  ("noodle", "ราดหน้าเจ", "", "เส้นราดน้ำแป้ง", "เส้นใหญ่ น้ำข้น ข้าวโพดอ่อน คะน้า"),
  ("noodle", "ก๋วยจั๊บญวนเจ", "", "ก๋วยจั๊บน้ำใส", "เส้นก๋วยจั๊บในน้ำซุปใส ใส่เต้าหู้"),
  ("rice", "ผัดมะเขือเจ", "", "มะเขือยาวผัด", "มะเขือยาวผัด"),
  ("rice", "ลาบเจ", "", "ลาบเต้าหู้หรือเห็ด", "เต้าหู้ เห็ด หรือแป้งทอด ปรุงแบบลาบ กาดหลวงขายปี 2568"),
  ("rice", "น้ำพริกหนุ่มเจ", "", "น้ำพริกหนุ่ม", "พริกหนุ่มย่างตำ ไม่มีน้ำปลาไม่มีกระเทียม"),
  ("rice", "หมูแดงเจ", "", "หมูแดงจากหมี่กึง", "หมี่กึงหรือโปรตีนเกษตร หน้าตาเหมือนหมูแดง"),
  ("snack", "เต้าหู้ทอด เผือกทอด", "", "ของทอด", "เต้าหู้ เผือก หัวไชเท้า ข้าวโพด ทอด"),
  ("snack", "ฟองเต้าหู้ทอด", "", "ฟองเต้าหู้กรอบ", "แผ่นจากผิวน้ำเต้าหู้ ตากแห้ง ทอดกรอบ"),
  ("snack", "ปอเปี๊ยะทอดเจ", "", "ปอเปี๊ยะทอด", "ของว่างง่าย ๆ ช่วงเทศกาล (เคทีซี)"),
  ("sweet", "น้ำเต้าหู้", "豆漿", "นมถั่วเหลือง", "น้ำเต้าหู้ร้อน ใส่ธัญพืช"),
  ("sweet", "เต้าฮวยน้ำขิง", "豆花", "เต้าฮวยน้ำขิง", "เต้าฮวยนิ่มในน้ำขิงร้อน"),
  ("sweet", "บัวลอยเผือกเจ", "", "บัวลอยในกะทิ", "บัวลอยเผือกในกะทิอุ่น"),
  ("sweet", "กล้วยบวชชีเจ", "", "กล้วยในกะทิ", "กล้วยต้มในกะทิหวาน"),
 ],
}

UI["en"].update({
 "title": "Kin Jay", "other_title": "กินเจ",
 "desc": "The Vegetarian Festival, 10–18 October 2026: the yellow 齋 flag, what stays off the plate, the menu, the shrines, halls and jay kitchens of Chiang Mai and Chiang Rai, Thailand's vegetarian groups, and the legends.",
 "card_alt": "Yellow jay flags with the red character 齋 strung across a street at dusk, steam rising from woks",
 "hero_alt": "A street at dusk strung with yellow pennants, each with the red character 齋, swaying over food stalls",
 "kicker": "The Vegetarian Festival · Thailand",
 "lede": "Nine days. Yellow flags over the woks, no garlic, white clothes.",
 "hint": "Tap the street.",
 "cardline": "10–18 Oct 2026 · 齋 · เจ",
 "dates_short": "10–18 Oct 2026",
 "now_in": "Today is day {n} of 9.", "now_before": "Starts in {n} days.", "now_tomorrow": "Starts tomorrow; today is the clean-out day.",
 "now_after": "Over for 2026. Next: 30 Sep–8 Oct 2027.",
 "nav_label": "Sections",
 "nav": [("days", "Nine days"), ("flag", "The flag"), ("rules", "Rules"), ("menu", "Menu"), ("north", "Chiang Mai · Chiang Rai"), ("thailand", "Thailand"), ("groups", "Groups"), ("legends", "Legends"), ("words", "Words"), ("sources", "Sources")],
 "lang_this": "EN", "lang_other": "ไทย",
 "days_kick": "The ninth month, days 1 to 9", "days_h": "Nine days, nine lamps",
 "days_p": ["The 1st to 9th of the ninth Chinese month: 10–18 October 2026. Strict keepers keep nine lamps burning the whole time."],
 "lamps_alt": "Nine oil lamps in a row, one for each day of the festival; the lamps up to today are lit",
 "day_short": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7", "Day 8", "Day 9"],
 "day_dates": ["10 Oct", "11 Oct", "12 Oct", "13 Oct", "14 Oct", "15 Oct", "16 Oct", "17 Oct", "18 Oct"],
 "day_dates_long": ["Saturday 10 October · day 1", "Sunday 11 October · day 2", "Monday 12 October · day 3", "Tuesday 13 October · day 4", "Wednesday 14 October · day 5", "Thursday 15 October · day 6", "Friday 16 October · day 7", "Saturday 17 October · day 8", "Sunday 18 October · day 9"],
 "days": [
  [DAYS[0], "The first day of jay. In Phuket the lantern pole (ko teng) went up the evening before, bringing in the nine lamps. In Chiang Mai the Guan Im foundation's rites and the Thailand J Food Festival at the two Central malls are already a day in."],
  [DAYS[1], "Phuket's shrine processions begin, one or more through town each day until the 18th."],
  [DAYS[2], "Day 3. Jay kitchens keep the yellow flag up all nine days; most cook from early morning and close by mid-afternoon."],
  [DAYS[3], "Day 4. Some people keep one day, some three, some all nine; Thailand Foundation's account of the Phuket festival says the intention is what counts."],
  [DAYS[4], "Day 5, the middle of the nine."],
  [DAYS[5], "Day 6."],
  [DAYS[6], "Day 7."],
  [DAYS[7], "Day 8."],
  [DAYS[8], "The last day. Jay ends after midnight, as the night of the 18th turns into the 19th."],
 ],
 "dates": [
  ("9 Oct 2026", "<b>Clean-out day</b> (lang thong): strict keepers eat jay the day before, to start clean."),
  ("10–18 Oct 2026", "<b>The nine days</b>, 1st to 9th of the ninth Chinese month."),
  ("Night of 18 Oct", "<b>Jay ends</b> after midnight, into the 19th."),
  ("30 Sep–8 Oct 2027", "<b>Next year</b>, per Kapook's 2027 calendar."),
 ],
 "days_note": "",
 "flag_kick": "The flag", "flag_h": "Red on yellow: <span class=\"zh\" lang=\"zh-Hant\">齋</span> · <span lang=\"th\">เจ</span>",
 "flag_p": ["Hang the yellow flag and you are telling the street: nothing from an animal in this food. Chinese signs write 齋. Thai signs spell it เจ."],
 "glyph_alt": "The characters 齊 and 示 sliding together into 齋 on a yellow flag",
 "g_l1": "齊 in order", "g_l2": "示 worship", "g_l3": "Chinese signs", "g_l4": "Thai signs",
 "glyph_hint": "Tap to replay.",
 "flag_facts": [["Readings", "jay in Thai, chai in Hokkien, zhāi in Mandarin, chay in Vietnamese; simplified Chinese 斋"], ["Yellow", "once kept for royalty and exorcists, so read as the colour of Buddhism and the precepts (Thai Wikipedia)"], ["Red", "good fortune"], ["White", "what keepers wear"]],
 "rules_kick": "What stays off the plate", "rules_h": "Jay or not?",
 "rules_p": ["No meat, fish, egg, milk, honey, fish sauce or oyster sauce. No pungent five, either: that is the line between jay and vegetarian."],
 "wok_alt": "A wok over a flame, with the ingredients you pick tumbling in, and a yellow flag on its pole that drops when something is not jay",
 "wok_h": "Tap ingredients into the wok.",
 "wok_clear": "Empty the wok",
 "wok_empty": "The wok is empty.",
 "wok_ok": "<b>Still jay.</b> The flag stays up.",
 "wok_no": "<b>Not jay any more:</b>",
 "rules": [
  ("Garlic", "กระเทียม"), ("Onions of every kind", "หอม: spring onion, shallot, onion"), ("Garlic chives", "กุยช่าย"),
  ("Chinese garlic, lak kiao", "หลักเกียว, a small single-clove garlic"), ("Tobacco leaf, or coriander", "depending on whose list"),
  ("Also", "No alcohol. The strict cook in pots that have never held meat, keep the five precepts, keep their speech gentle and abstain from sex."),
 ],
 "menu_kick": "Menu", "menu_h": "What the kitchens cook",
 "menu_p": ["Thai and Chinese cooking with the meat and the pungent five taken out."],
 "menu_all": "All", "menu_kinds": [("noodle", "Noodles"), ("soup", "Soups"), ("rice", "With rice"), ("curry", "Curries"), ("snack", "Fried"), ("sweet", "Sweet")],
 "menu_note": "From festival menu lists in Thansettakij, Thairath and Chiang Mai News.",
 "north_kick": "Chiang Mai · Chiang Rai", "north_h": "Where the north keeps it",
 "north_p": ["Chiang Mai keeps it around Warorot and the Chinese shrines on the Ping; Chiang Rai at its old-town shrine and up in Mae Sai. Every place opens on Mot Dang."],
 "north_events": [
  {"name": "Guan Im Dhamma Dan Foundation", "when": "9–18 Oct 2026", "where": "Mueang Samut Road, Chiang Mai", "what": "Rites led by Chinese monks from Wat Muen Puttha Mettakhunaram, Mae Chan. White clothes for the rites; 053-235-968.", "src": "https://www.chiangmainews.co.th/social/4146691/"},
  {"name": "Thailand J Food Festival 2026", "when": "9–18 Oct 2026", "where": "Central Chiang Mai and Central Chiang Mai Airport", "what": "Jay dishes, a J Market of more than twenty brands, and workshops.", "src": "https://www.thethaipress.com/2026/171849"},
  {"name": "Pung Tao Kong Shrine", "when": "2025: all nine days", "where": "by Warorot, Chiang Mai", "what": "Free jay meals at 11:00–12:00 and 16:00–17:00. No 2026 notice seen by 7 Oct.", "src": "https://www.cmhy.city/event/1618-You-are-invited-to-join-the-Vegetarian-Festival-at-the-Pung-Tao-Kong-Shrine-Chiang-Mai-2025"},
  {"name": "Warorot market", "when": "2025", "where": "Kad Luang, Chiang Mai", "what": "Yellow flags across the market; one jay stall cooked about twenty dishes a day at 35–40 baht a box.", "src": "https://www.chiangmainews.co.th/news/chiangmai/3797300/"},
  {"name": "Kuang Meng Foundation free kitchen", "when": "2025", "where": "Mae Sai, Chiang Rai", "what": "A free jay kitchen, 11:30–14:00: rice, glass-noodle stir-fry, tofu soup, pumpkin curry, ginger and soy drinks.", "src": "https://www.lemon8-app.com/@viewolet/7563606336190841352?region=th"},
  {"name": "Jay food centre, Wiang", "when": "2023", "where": "Mueang Chiang Rai", "what": "Open 07:00–15:00 through the festival, meals at 30, 40 and 45 baht.", "src": "https://www.chiangmainews.co.th/news/chiangrai/3114216/"},
 ],
 "map_h": "Halls and kitchens on the map", "map_views": [("city", "Old city & Warorot"), ("cm", "Chiang Mai"), ("cr", "Chiang Rai"), ("crtown", "Chiang Rai town")],
 "map_alt": "A map of shrines, jay halls and jay kitchens in Chiang Mai and Chiang Rai; tap a dot for its name",
 "map_hall": "Shrine or jay hall", "map_kitchen": "Jay or vegetarian kitchen", "map_other": "Market, mall, gurdwara, temple",
 "map_hint": "Tap a dot.", "map_open": "On Mot Dang →", "map_ping": "Ping River",
 "cm_halls": "Chiang Mai: shrines and halls", "cm_kitchens": "Chiang Mai: jay kitchens", "cm_other": "Chiang Mai: also",
 "cr_halls": "Chiang Rai: shrines and halls", "cr_kitchens": "Chiang Rai: jay kitchens", "cr_other": "Chiang Rai: also",
 "north_note": "Festival hours can differ from the listing.",
 "src_word": "Source",
 "foot": "Kin Jay · text CC BY 4.0, code MIT",
 "src_h": "Sources", "src_p": "",
 "map_credit": "Amphoe outlines: OCHA COD-AB Thailand, Royal Thai Survey Department, CC BY-IGO. Water: © OpenStreetMap contributors, ODbL. Places: Mot Dang.",
 "words_h": "Words",
})

UI["th"].update({
 "title": "กินเจ", "other_title": "Kin Jay",
 "desc": "เทศกาลกินเจ 10–18 ตุลาคม 2569 ธงเหลืองตัว 齋 อะไรกินได้ อะไรต้องงด เมนูเจ ศาลเจ้า โรงเจ และร้านเจในเชียงใหม่และเชียงราย กลุ่มคนกินเจและมังสวิรัติในไทย และตำนาน",
 "card_alt": "ธงเจสีเหลืองตัวอักษร 齋 สีแดง ขึงข้ามถนนตอนพลบค่ำ ไอร้อนลอยจากกระทะ",
 "hero_alt": "ถนนตอนพลบค่ำ ขึงธงสามเหลี่ยมสีเหลืองตัว 齋 สีแดง ปลิวเหนือแผงอาหาร",
 "kicker": "เทศกาลกินเจ · ทั่วไทย",
 "lede": "เก้าวัน ธงเหลืองเหนือกระทะ งดกระเทียม ใส่ชุดขาว",
 "hint": "แตะถนน",
 "cardline": "10–18 ต.ค. 2569 · 齋 · เจ",
 "dates_short": "10–18 ต.ค. 2569",
 "now_in": "วันนี้วันที่ {n} จาก 9 วัน", "now_before": "อีก {n} วันเริ่ม", "now_tomorrow": "พรุ่งนี้เริ่ม วันนี้วันล้างท้อง",
 "now_after": "ปี 2569 จบแล้ว ปีหน้า 30 ก.ย.–8 ต.ค. 2570",
 "nav_label": "หัวข้อ",
 "nav": [("days", "เก้าวัน"), ("flag", "ธงเจ"), ("rules", "ข้อห้าม"), ("menu", "เมนู"), ("north", "เชียงใหม่ · เชียงราย"), ("thailand", "ทั่วไทย"), ("groups", "กลุ่ม"), ("legends", "ตำนาน"), ("words", "คำ"), ("sources", "ที่มา")],
 "lang_this": "ไทย", "lang_other": "EN",
 "days_kick": "ขึ้น 1 ค่ำ ถึง 9 ค่ำ เดือน 9 จีน", "days_h": "เก้าวัน เก้าตะเกียง",
 "days_p": ["ขึ้น 1–9 ค่ำ เดือน 9 จีน ตรงกับ 10–18 ตุลาคม 2569 คนที่เคร่งจุดตะเกียงเก้าดวงไว้ไม่ให้ดับตลอดเก้าวัน"],
 "lamps_alt": "ตะเกียงน้ำมันเก้าดวงเรียงกัน หนึ่งดวงต่อหนึ่งวัน ดวงที่ถึงวันนี้แล้วจุดไฟอยู่",
 "day_short": ["วัน 1", "วัน 2", "วัน 3", "วัน 4", "วัน 5", "วัน 6", "วัน 7", "วัน 8", "วัน 9"],
 "day_dates": ["10 ต.ค.", "11 ต.ค.", "12 ต.ค.", "13 ต.ค.", "14 ต.ค.", "15 ต.ค.", "16 ต.ค.", "17 ต.ค.", "18 ต.ค."],
 "day_dates_long": ["เสาร์ 10 ตุลาคม · วันที่ 1", "อาทิตย์ 11 ตุลาคม · วันที่ 2", "จันทร์ 12 ตุลาคม · วันที่ 3", "อังคาร 13 ตุลาคม · วันที่ 4", "พุธ 14 ตุลาคม · วันที่ 5", "พฤหัสบดี 15 ตุลาคม · วันที่ 6", "ศุกร์ 16 ตุลาคม · วันที่ 7", "เสาร์ 17 ตุลาคม · วันที่ 8", "อาทิตย์ 18 ตุลาคม · วันที่ 9"],
 "days": [
  [DAYS[0], "วันแรกของการกินเจ ที่ภูเก็ตยกเสาโกเต้งไปแล้วเมื่อเย็นวันก่อน พร้อมตะเกียงเก้าดวง ที่เชียงใหม่ พิธีของมูลนิธิกวนอิมธรรมทานและงาน Thailand J Food Festival ที่เซ็นทรัลสองแห่งเริ่มไปแล้วหนึ่งวัน"],
  [DAYS[1], "ภูเก็ตเริ่มขบวนแห่ของศาลเจ้า มีขบวนออกทุกวันจนถึงวันที่ 18"],
  [DAYS[2], "วันที่ 3 ร้านเจขึ้นธงเหลืองครบเก้าวัน ส่วนใหญ่ทำกับข้าวตั้งแต่เช้ามืดและปิดราวบ่าย"],
  [DAYS[3], "วันที่ 4 บางคนกินวันเดียว บางคนสามวัน บางคนครบเก้าวัน มูลนิธิไทย (Thailand Foundation) เล่าถึงงานที่ภูเก็ตว่าเจตนาคือสิ่งที่นับ"],
  [DAYS[4], "วันที่ 5 กลางเทศกาล"],
  [DAYS[5], "วันที่ 6"],
  [DAYS[6], "วันที่ 7"],
  [DAYS[7], "วันที่ 8"],
  [DAYS[8], "วันสุดท้าย ออกเจหลังเที่ยงคืน ตอนคืนวันที่ 18 ต่อเช้าวันที่ 19"],
 ],
 "dates": [
  ("9 ต.ค. 2569", "<b>วันล้างท้อง</b> คนที่เคร่งกินเจก่อนหนึ่งวัน ให้ท้องสะอาดก่อนเริ่ม"),
  ("10–18 ต.ค. 2569", "<b>เก้าวันกินเจ</b> ขึ้น 1–9 ค่ำ เดือน 9 จีน"),
  ("คืนวันที่ 18 ต.ค.", "<b>ออกเจ</b> หลังเที่ยงคืน เข้าวันที่ 19"),
  ("30 ก.ย.–8 ต.ค. 2570", "<b>ปีหน้า</b> ตามปฏิทินปี 2570 ของ Kapook"),
 ],
 "days_note": "",
 "flag_kick": "ธงเจ", "flag_h": "อักษรแดงบนผ้าเหลือง <span class=\"zh\" lang=\"zh-Hant\">齋</span> · เจ",
 "flag_p": ["ธงเหลืองบอกคนทั้งถนนว่าอาหารร้านนี้ไม่มีของจากสัตว์ ป้ายจีนเขียน 齋 ป้ายไทยเขียน เจ"],
 "glyph_alt": "อักษร 齊 กับ 示 เลื่อนมารวมกันเป็น 齋 บนธงเหลือง",
 "g_l1": "齊 เป็นระเบียบ", "g_l2": "示 บูชา", "g_l3": "ป้ายจีน", "g_l4": "ป้ายไทย",
 "glyph_hint": "แตะเพื่อดูอีกครั้ง",
 "flag_facts": [["อ่านว่า", "เจ หรือไจ ฮกเกี้ยน chai จีนกลาง zhāi เวียดนาม chay จีนตัวย่อ 斋"], ["สีเหลือง", "แต่ก่อนใช้ได้เฉพาะเจ้านายกับอาจารย์ปราบผี จึงถือเป็นสีของพุทธศาสนาและผู้ถือศีล (วิกิพีเดียภาษาไทย)"], ["สีแดง", "สิริมงคล"], ["สีขาว", "ชุดของคนถือศีล"]],
 "rules_kick": "อะไรต้องงด", "rules_h": "เจหรือไม่เจ",
 "rules_p": ["งดเนื้อสัตว์ ปลา ไข่ นม น้ำผึ้ง น้ำปลา ซอสหอยนางรม และงดผักฉุนห้าอย่าง ซึ่งเป็นเส้นแบ่งระหว่างเจกับมังสวิรัติ"],
 "wok_alt": "กระทะบนเตาไฟ ของที่เลือกตกลงไปในกระทะ ธงเหลืองบนเสาจะลดลงเมื่อมีของที่ไม่เจ",
 "wok_h": "แตะวัตถุดิบใส่กระทะ",
 "wok_clear": "เทกระทะ",
 "wok_empty": "กระทะยังว่าง",
 "wok_ok": "<b>ยังเจอยู่</b> ธงยังขึ้น",
 "wok_no": "<b>ไม่เจแล้ว</b>",
 "rules": [
  ("กระเทียม", "garlic"), ("หอมทุกชนิด", "ต้นหอม หอมแดง หอมหัวใหญ่"), ("กุยช่าย", "garlic chives"),
  ("หลักเกียว", "กระเทียมโทนจีน"), ("ใบยาสูบ หรือผักชี", "แล้วแต่ตำรา"),
  ("และ", "งดเหล้า คนที่เคร่งใช้ภาชนะแยกจากของคาว ถือศีลห้า พูดจาสุภาพ และงดเพศสัมพันธ์"),
 ],
 "menu_kick": "เมนู", "menu_h": "ครัวเจทำอะไรกิน",
 "menu_p": ["กับข้าวไทยและจีนที่เอาเนื้อสัตว์และผักฉุนออก"],
 "menu_all": "ทั้งหมด", "menu_kinds": [("noodle", "เส้น"), ("soup", "ต้ม ซุป"), ("rice", "กับข้าว"), ("curry", "แกง"), ("snack", "ของทอด"), ("sweet", "ของหวาน")],
 "menu_note": "เมนูจากรายการช่วงเทศกาลของฐานเศรษฐกิจ ไทยรัฐ และเชียงใหม่นิวส์",
 "north_kick": "เชียงใหม่ · เชียงราย", "north_h": "กินเจที่ภาคเหนือ",
 "north_p": ["เชียงใหม่กินเจรอบกาดหลวงและศาลเจ้าจีนริมน้ำปิง เชียงรายที่ศาลเจ้าในเมืองเก่าและที่แม่สาย ทุกที่เปิดดูในมดแดงได้"],
 "north_events": [
  {"name": "มูลนิธิกวนอิมธรรมทาน", "when": "9–18 ต.ค. 2569", "where": "ถนนเมืองสมุทร เชียงใหม่", "what": "พระสงฆ์จีนจากวัดหมื่นพุทธเมตตาคุณาราม แม่จัน นำสวด ใส่ชุดขาวเข้าพิธี โทร 053-235-968", "src": "https://www.chiangmainews.co.th/social/4146691/"},
  {"name": "Thailand J Food Festival 2026", "when": "9–18 ต.ค. 2569", "where": "เซ็นทรัล เชียงใหม่ และเซ็นทรัล เชียงใหม่ แอร์พอร์ต", "what": "อาหารเจ J Market กว่ายี่สิบแบรนด์ และเวิร์กช็อป", "src": "https://www.thethaipress.com/2026/171849"},
  {"name": "ศาลเจ้าปุงเถ่ากง", "when": "ปี 2568 ครบเก้าวัน", "where": "ข้างกาดหลวง เชียงใหม่", "what": "แจกอาหารเจฟรี 11.00–12.00 และ 16.00–17.00 น. ปี 2569 ยังไม่เห็นประกาศ ณ 7 ต.ค.", "src": "https://www.cmhy.city/event/1618-You-are-invited-to-join-the-Vegetarian-Festival-at-the-Pung-Tao-Kong-Shrine-Chiang-Mai-2025"},
  {"name": "กาดหลวง (ตลาดวโรรส)", "when": "ปี 2568", "where": "เชียงใหม่", "what": "ธงเหลืองขึ้นทั่วตลาด แผงเจแผงหนึ่งทำกับข้าวราวยี่สิบอย่างต่อวัน กล่องละ 35–40 บาท", "src": "https://www.chiangmainews.co.th/news/chiangmai/3797300/"},
  {"name": "โรงทานเจ มูลนิธิกวงเม้ง", "when": "ปี 2568", "where": "แม่สาย เชียงราย", "what": "โรงทานเจ 11.30–14.00 น. ข้าว ผัดวุ้นเส้น ต้มเต้าหู้ แกงฟักทอง น้ำขิง น้ำเต้าหู้", "src": "https://www.lemon8-app.com/@viewolet/7563606336190841352?region=th"},
  {"name": "ศูนย์อาหารธรรมชาติเจ ตำบลเวียง", "when": "ปี 2566", "where": "อำเภอเมืองเชียงราย", "what": "เปิด 07.00–15.00 น. ตลอดเทศกาล ข้าวจานละ 30, 40, 45 บาท", "src": "https://www.chiangmainews.co.th/news/chiangrai/3114216/"},
 ],
 "map_h": "ศาลเจ้าและร้านเจบนแผนที่", "map_views": [("city", "เมืองเก่าและกาดหลวง"), ("cm", "เชียงใหม่"), ("cr", "เชียงราย"), ("crtown", "ตัวเมืองเชียงราย")],
 "map_alt": "แผนที่ศาลเจ้า โรงเจ และร้านเจในเชียงใหม่และเชียงราย แตะจุดเพื่อดูชื่อ",
 "map_hall": "ศาลเจ้า โรงเจ", "map_kitchen": "ร้านเจ ร้านมังสวิรัติ", "map_other": "ตลาด ห้าง คุรุดวารา เทวสถาน",
 "map_hint": "แตะที่จุด", "map_open": "ดูในมดแดง →", "map_ping": "แม่น้ำปิง",
 "cm_halls": "เชียงใหม่: ศาลเจ้าและโรงเจ", "cm_kitchens": "เชียงใหม่: ร้านเจ", "cm_other": "เชียงใหม่: ที่อื่น",
 "cr_halls": "เชียงราย: ศาลเจ้าและโรงเจ", "cr_kitchens": "เชียงราย: ร้านเจ", "cr_other": "เชียงราย: ที่อื่น",
 "north_note": "เวลาเปิดช่วงเทศกาลอาจต่างจากที่ลงไว้",
 "src_word": "ที่มา",
 "foot": "กินเจ · ข้อความ CC BY 4.0 โค้ด MIT",
 "src_h": "ที่มา", "src_p": "",
 "map_credit": "เส้นเขตอำเภอ: OCHA COD-AB Thailand กรมแผนที่ทหาร CC BY-IGO แม่น้ำ: © ผู้ร่วมสร้าง OpenStreetMap ODbL สถานที่: มดแดง",
 "words_h": "คำ",
})

for lang in ("en", "th"):
    UI[lang]["foods"] = FOODS[lang]
    UI[lang]["dishes"] = [{"k": k, "name": n, "zh": z, "gloss": g, "what": w} for k, n, z, g, w in DISHES[lang]]

# filled from research-national: groups, tales, thai_events, words, PHOTOS, SOURCES
from copy_more import more  # noqa: E402
PHOTOS, SOURCES = more(UI)
